# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source 'https://rubygems.org/'

gem 'hoe', '~>3.12', group: [:development, :test]
gem 'hoe-bundler'
gem 'hoe-debugging'
gem 'hoe-gemspec'
gem 'hoe-git'
gem 'minitest'
gem 'rake'
gem 'rake-compiler', '~>0.9.2', group: [:development, :test]
gem 'rake-compiler-dock', '~>0.5.1', group: [:development, :test]
gem 'rdoc', '~>4.0', group: [:development, :test]
gem 'rspec', group: [:development, :test]
gem 'test-unit', group: [:development, :test]
gem 'yard', group: [:development, :test]

# vim: syntax=ruby
