# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source 'https://rubygems.org/'

gem 'hoe', '~>3.12', group: [:development, :test]
gem 'hoe-bundler', '~>1.2.0', group: [:development, :test]
gem 'hoe-debugging', '~>1.2.1', group: [:development, :test]
gem 'hoe-gemspec', '~>1.0.0', group: [:development, :test]
gem 'hoe-git', '~>1.6.0', group: [:development, :test]
gem 'minitest', '~>5.8.4', group: [:development, :test]
gem 'rake', '~>10.5.0', group: [:development, :test]
gem 'rake-compiler', '~>0.9.2', group: [:development, :test]
gem 'rake-compiler-dock', '~>0.5.1', group: [:development, :test]
gem 'rdoc', '~>4.0', group: [:development, :test]
gem 'test-unit', group: [:development, :test]

# vim: syntax=ruby
