# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source 'https://rubygems.org/'

gemspec

gem 'hoe', '~>3.12', group: [:development, :test]
gem 'rake-compiler', '~>0.9.2', group: [:development, :test]
gem 'rake-compiler-dock', '~>0.5.1', group: [:development, :test]
gem 'rdoc', '~>4.0', group: [:development, :test]
gem 'test-unit', group: [:development, :test]

# vim: syntax=ruby
